"""Add geo

Revision ID: 5209f75543b2
Revises: 266ab139e8ab
Create Date: 2014-06-05 18:57:00.687812

"""

# revision identifiers, used by Alembic.
revision = '5209f75543b2'
down_revision = '266ab139e8ab'

from alembic import op
import sqlalchemy as sa
import geoalchemy2 as ga


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Unicode(length=255), nullable=False),
                    sa.Column('admin_level', sa.Integer(), nullable=False),
                    sa.Column('admin_type',
                              sa.Unicode(length=64),
                              nullable=False),
                    sa.Column('boundary', ga.Geometry(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('boundary_idx',
                    'region',
                    ['boundary'],
                    unique=False,
                    postgresql_using='gist'
                    )
    op.create_index(op.f('ix_region_admin_level'),
                    'region',
                    ['admin_level'],
                    unique=False)
    op.create_index(op.f('ix_region_name'), 'region', ['name'], unique=False)
    op.create_table('region_hierarchy',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('inner_id', sa.Integer(), nullable=False),
                    sa.Column('outer_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['inner_id'], ['region.id'], ),
                    sa.ForeignKeyConstraint(['outer_id'], ['region.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('region_simplified',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('region_id', sa.Integer(), nullable=False),
                    sa.Column('tolerance', sa.Float(), nullable=False),
                    sa.Column('boundary', ga.Geometry(), nullable=False),
                    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('instance',
                  sa.Column('geo_centre', ga.Geometry(), nullable=True))
    op.add_column('instance',
                  sa.Column('region_id', sa.Integer(), nullable=True))
    op.add_column('instance',
                  sa.Column('use_maps', sa.Boolean(), nullable=True))
    op.create_index('geo_centre_idx',
                    'instance',
                    ['geo_centre'],
                    unique=False,
                    postgresql_using='gist')
    op.add_column('page', sa.Column('geotag', ga.Geometry(), nullable=True))
    op.add_column('proposal',
                  sa.Column('geotag', ga.Geometry(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal', 'geotag')
    op.drop_column('page', 'geotag')
    op.drop_index('geo_centre_idx', table_name='instance')
    op.drop_column('instance', 'use_maps')
    op.drop_column('instance', 'region_id')
    op.drop_column('instance', 'geo_centre')
    op.drop_table('region_simplified')
    op.drop_table('region_hierarchy')
    op.drop_index(op.f('ix_region_name'), table_name='region')
    op.drop_index(op.f('ix_region_admin_level'), table_name='region')
    op.drop_index('boundary_idx', table_name='region')
    op.drop_table('region')
    ### end Alembic commands ###
