
from ..types import *

N_DELEGATION_RECEIVED = "n_delegation_receive"
N_DELEGATION_LOST = "n_delegation_lost"

N_SELF_VOTED = "n_self_voted"
N_DELEGATE_VOTED = "n_delegate_voted"
N_DELEGATE_CONFLICT = "n_delegate_conflict"

N_INSTANCE_FORCE_LEAVE = "n_instance_force_leave"
N_INSTANCE_MEMBERSHIP_UPDATE = "n_instance_membership_update"

N_COMMENT_REPLY = "n_comment_reply"
N_COMMENT_EDIT = "n_comment_edit"


PRIORITIES = {
    T_USER_CREATE: 2,
    T_USER_EDIT: 1,
    T_USER_ADMIN_EDIT: 2,
    T_INSTANCE_CREATE: 3,
    T_INSTANCE_EDIT: 3,
    T_INSTANCE_DELETE: 3,
    T_INSTANCE_JOIN: 2,
    T_INSTANCE_LEAVE: 2,
    T_INSTANCE_FORCE_LEAVE: 3,
    T_INSTANCE_MEMBERSHIP_UPDATE: 3,
    T_ISSUE_CREATE: 3,
    T_ISSUE_EDIT: 1,
    T_ISSUE_DELETE: 2,
    T_MOTION_CREATE: 3,
    T_MOTION_EDIT: 1,
    T_MOTION_STATE_REDRAFT: 3,
    T_MOTION_STATE_VOTING: 4,
    T_MOTION_DELETE: 2,
    T_CATEGORY_CREATE: 2,
    T_CATEGORY_EDIT: 1,
    T_CATEGORY_DELETE: 3,
    T_COMMENT_CREATE: 2,
    T_COMMENT_EDIT: 1,
    T_COMMENT_DELETE: 2,
    T_DELEGATION_CREATE: 2,
    T_DELEGATION_REVOKE: 2,
    T_VOTE_CAST: 1,
    T_TEST: 4,
    
    N_DELEGATION_RECEIVED: 3,
    N_DELEGATION_LOST: 3,
    N_SELF_VOTED: 3,
    N_DELEGATE_VOTED: 4,
    N_DELEGATE_CONFLICT: 5,
    N_INSTANCE_FORCE_LEAVE: 5,
    N_INSTANCE_MEMBERSHIP_UPDATE: 4,
    N_COMMENT_REPLY: 4,
    N_COMMENT_EDIT: 4
    }